# Site settings
title: aalmiramolla web page
email: aalmiramolla@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    My own, personal webpage, where I promote me and write about computer topics.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://aalmiramolla.github.io" # the base hostname & protocol for your site
twitter_username: aalmiramolla
github_username:  aalmiramolla

# Build settings
markdown: kramdown

collections:
  - projects